### ISSUE TITLE
Water bleeding

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#130]
Just for reference, the water bleeding we talked about may want an improvement at some point.

(Legs)

![edison-water-bleeding](https://user-images.githubusercontent.com/4934209/108611439-cfbaec80-73de-11eb-9435-b2d9e5958f90.jpg)

**Comment by stohrendorf** [comment]
I'm tempted to close this one, because that requires a huge amount of work for minor benefits IHMO.

**Comment by Richard-L** [comment]
Very much understand. Maybe give it some time until more people other than me have reacted to the water. I think you might alter it some in the future, where this bleeding issue can be re-assessed then.
