### ISSUE TITLE
Reduce wave reflection or increase performance

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#134]
Currently the reflections of the water surfaces is too strong, to the point where you can't see.

Moreso the moment of going underwater, and coming close to the wave reflections, is a massive performance hit currently and would need improvement.

**Comment by stohrendorf** [comment]
Interesting... as I haven't implemented reflections, I don't know what you mean. Could share a screenshot maybe?

**Comment by Richard-L** [comment]
The water is super cool, don't get me wrong. But during these moments of entering it, you lose vision almost entirely, as Lara disappears. Especially since it's usually combined with quite a hefty performance hit and consequent slowdown, until the camera is underwater and the game resumes to full speed:

![2021-02-22 23-55-42](https://user-images.githubusercontent.com/4934209/108782190-6a483680-756b-11eb-8be5-c05ddbbb370f.png)
![2021-02-22 23-55-44](https://user-images.githubusercontent.com/4934209/108782194-6caa9080-756b-11eb-9ac1-58c57ff794ca.png)
