### ISSUE TITLE
Music playing simultaneously

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#135]
At this point in the level, the TR main theme begins playing:

![image](https://user-images.githubusercontent.com/4934209/108611593-43a9c480-73e0-11eb-8222-da5fa16b06ce.png)

The Cave Echoes does not stop playing however, meaning both tracks are overlaid which is unwanted behaviour. The Cave Echoes should stop, and resume once the interlude has finished.

Further, the interlude is not part of quicksaves. On quickload, it should either replay, or ideally have music position remembered and continue playback from timestamp.

The same happens for all other music tracks (ie Cave Echoes never stops).

**Comment by stohrendorf** [comment]
These are essentially two issues.
* The overlaying music, that is on purpose, as the original engine relied on CD tracks for this, and you could only play one track at a time. It is diffent, yes, but I never saw anything where this is actually disturbing.
* Saving music positions and whether a track was played already. I'm aware of this (sometimes) - it just happens so rarely that I never got around on writing an issue for this.

**Comment by Richard-L** [comment]
My advice would be to mimick audio track playback behaviour here. TR used music very acutely to change focus or atmosphere, and the cave echoes staying on in the back is a very odd, and to my ears un-TR-like, effect.

**Comment by Richard-L** [comment]
Somewhat related to this moment of the player dying https://github.com/stohrendorf/EdisonEngine/issues/140 ... the music should stop upon Lara's death to create a sober moment of silence.
