### ISSUE TITLE
Items missing in inventory

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#136]
The inventory does not list any pickups other than these:

![image](https://user-images.githubusercontent.com/4934209/108611643-c9c60b00-73e0-11eb-9474-73add861c695.png)

At this point it should show magnum clips I had picked up, as well as one of the wheels from Lost Valley.

**Comment by stohrendorf** [comment]
Can't reproduce this. Checked in debug and release builds.

**Comment by stohrendorf** [comment]
Sorry, my bad, ammo was in fact missing.

**Comment by stohrendorf** [comment]
The cog is added to the inventory, it's two rings down in the "items" ring.

**Comment by Richard-L** [comment]
Would recommend to follow vanilla ring order.

https://user-images.githubusercontent.com/4934209/108641817-aca54100-74a1-11eb-91df-01ef489aca34.mp4
