### ISSUE TITLE
Keyhole Lara Angling misses stance correction

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#137]
Currently you can insert keys or keyhole items from an angle, without Lara resetting to a perpendicular stance:

![image](https://user-images.githubusercontent.com/4934209/108611670-07c32f00-73e1-11eb-9444-4f3a784a6d05.png)

^this was immediately after inserting the item. Similar to how she corrects her position during a pick-up trigger, the game should reposition her automatically if you're standing within the bounding box.

**Comment by stohrendorf** [comment]
I could swear this works for me as you described it.
