### ISSUE TITLE
Wrong gun aim in Lost Valley

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#142]
![image](https://user-images.githubusercontent.com/4934209/108611841-e2cfbb80-73e2-11eb-9972-c44819ba0779.png)

![image](https://user-images.githubusercontent.com/4934209/108611845-e6634280-73e2-11eb-8b76-292d3396fe86.png)

At this spot Lara is aiming into the ceiling for some reason. Maybe a wrong enemy identification.

**Comment by stohrendorf** [comment]
That's the first time I see this behavior. Is it reproducible?
