### ISSUE TITLE
Skylight for Lost Valley?

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#143]
Consider the way OpenLara does it. I think it's worth adding one. Very subjective of course.

**Comment by stohrendorf** [comment]
The problem with this is that it won't work with the current visuals, i.e. the world is not rendered beyond 20 sectors, and fades to black after 12 sectors. Adding a sky would mean changing some fundamental looks.

**Comment by Richard-L** [comment]
I understand, that's tricky then. Generally this is a very optional thing. I just think it works wonders and is often applauded about OpenLara.

Perhaps is it possible to temporarily disable the fading completely?

**Comment by stohrendorf** [comment]
Maybe in the future once some (still present) rendering bugs are resolved and the game-play is stable.
