### ISSUE TITLE
T-Rex music gets retriggered in Lost Valley

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#144]
Even with the T-Rex defeated, the T-Rex music gets wrongfully retriggered and plays a second time when you walk back out of the valley, on your way to finish the level.

**Comment by stohrendorf** [comment]
Possibly related to #135.

**Comment by stohrendorf** [comment]
I can't reproduce this. Have you loaded a savegame between the first play and the second one? If not, could you give instruction how to trigger this bug?
