### ISSUE TITLE
Missing inventory trigger for Lost Valley wheels

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#146]
You can currently put these wheels in without selecting them from the inventory first (as would be expected behaviour):
![image](https://user-images.githubusercontent.com/4934209/108611932-e879d100-73e3-11eb-8063-cb1a2218a056.png)

Although it's actually kind of nice because it saves time, but just so you know it's not truthful to the original game.

**Comment by stohrendorf** [comment]
That's intentional, although it would probably make sense to still keep the option available to toggle this behaviour.

**Comment by Richard-L** [comment]
Found this for reference: https://youtu.be/D3qgf84dLDg?t=1124
