### ISSUE TITLE
Restart Level option

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#157]
This page is currently missing from the passport. Only available when inside a level. Possible this is PS1 only, but I would say that's the version you want to match.

![SLES-00024_2021-02-24_23-38-41](https://user-images.githubusercontent.com/4934209/109075840-fa1beb00-76f9-11eb-89cd-43b7c8d264f2.png)

**Comment by stohrendorf** [comment]
That page doesn't seem to be the last one in the passport. If that's the case, it's not even included in the game model. Although I like the idea, I doubt it's possible to copy that 1:1 and instead needs another mechanism to make it available.

**Comment by Richard-L** [comment]
XProger has dumped the files here I think: https://discord.com/channels/218414493355606016/309026200284823552/814506552329371689

Duckstation also has a texture dumping branch I could try for comparison if you like.

I just wonder how we'll make these assets available though, if you're saying they can't be sourced from the PC files?
