### ISSUE TITLE
Health and Breath Bars

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#160]
### Health bar

PS1 EU and US versions have it on the right:
![image](https://user-images.githubusercontent.com/4934209/109226629-60b70c80-77bf-11eb-8f2f-c7330f1dec13.png)

PS1 JP and PC versions have it on the left:
![image](https://user-images.githubusercontent.com/4934209/109227066-04082180-77c0-11eb-8272-2177315b56ec.png)
![image](https://user-images.githubusercontent.com/4934209/109227265-534e5200-77c0-11eb-8e24-5696c1996297.png)

I think the PC version screenshot shows the issue of resolution dependence regarding size and position. It's too far in the corner, and too small. In the current Alpha4 of EE, I'm afraid this is the same problem. Thus to fix this, it would be nice if for positioning and sizing, something pixel-independent could be found, or a [breakpoint system](https://lh4.googleusercontent.com/R9AyaT9KcaL6FX0M7z6HFIT9PMGtObPGA259mYuOxsGZw0761cyd9z2NKGsRNlcZJxlRNcFf5HGxy7w0qEM-_vKdQ07rPHE7RUZGxCXckU1gbT6eYmWuKHTN3fYbg_4N6usuqsI) like app designers use them (albeit that's getting a bit complicated perhaps). This is however touching on the bigger and more global topic of icon and element sizing inside EE.

Details on the health bar:

![image](https://user-images.githubusercontent.com/4934209/109229549-c1e0df00-77c3-11eb-88df-25732d6a984a.png)

- Equipping/unequipping weapons will make the health bar appear/disappear. Whilst equipped, the health bar always shows.
- Losing energy in any way will immediately show it reduced. There is no animation:

https://user-images.githubusercontent.com/4934209/109230834-cc9c7380-77c5-11eb-91f9-97eacdbc4570.mp4
^notice the time it takes for it to disappear again after the update. Sadly I cannot record and play at 100% speed so the timing is slightly off.

https://user-images.githubusercontent.com/4934209/109230471-3c5e2e80-77c5-11eb-993c-5d32d3542714.mp4
^after dying (I sped up emulation a bit here), the health bar keeps showing empty (black), even as the game overlays the menu and passport on the "Restart Level" page. cf https://github.com/stohrendorf/EdisonEngine/issues/157

### Breath bar

Analog to the health bar, it's on the left/right for the different versions respectively. It's always positioned under the health bar, so that when losing health underwater both can show simultaneously:
![image](https://user-images.githubusercontent.com/4934209/109234863-ca89e300-77cc-11eb-8a31-e085f37a0568.png)

When you die underwater but still have breath, it empties out immediately, to show two empty bars:
![image](https://user-images.githubusercontent.com/4934209/109235030-294f5c80-77cd-11eb-938b-416cb45bbb1b.png)

After filling up, it will keep showing up full until the player leaves water:
![image](https://user-images.githubusercontent.com/4934209/109235112-513ec000-77cd-11eb-9111-35c1f180a90c.png)

Breath lasts for 1min apparently as we worked out. It can also be seen in Raina's video: https://youtu.be/a0tZGgQnoj4
^Also can see how quickly the health bar depletes from loss of air.

### Some observations/thoughts

- All bars in all versions always fill up to the right when using health packs/surfacing in water
- The gradient inside them is of course very coarse stemming from the PS1 emulation. I just extracted all the colours there were for general reference.
- Do you think they should be on the left or right? Do you intend to make EE compatible other TR games? Might make sense to look into where they place them, for consistency.

**Comment by stohrendorf** [comment]
Maybe it could be an option to allow selecting between different layouts, e.g.
* health top left, air top right
* health top right, air top left
* stacked top right
* ... others?

About colors, these stem from the levels' palette data.

The behaviour (fading, when to display, etc.) of the bars should be split into a separate ticket.
