### ISSUE TITLE
Demo Mode

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#163]
Perhaps for something nice much later, you could consider adding the two demo modes playing on PS1 (and I think on PC too?) for "City of Vilcabama" and "Lost Valley" if nothing is chosen in the main menu for ~18sec (about 5 passport rotations ;))

![image](https://user-images.githubusercontent.com/4934209/109363386-c1f8e180-788c-11eb-95ae-cadebb8073ab.png)
![image](https://user-images.githubusercontent.com/4934209/109363396-c8875900-788c-11eb-9de7-9671848315f7.png)

**Comment by stohrendorf** [comment]
That would be a horrible task to do, because it would require replicating _every_ step of code of the original engine, as it's relying on the random number generator behaviour. So... no.
