### ISSUE TITLE
Items respawn after they have been used

### ISSUE THREAD

**Issue by ANoDE85** [stohrendorf/EdisonEngine#184]
Engine Version: Beta 6.1
Level: The Lost Valley

Current behaviour:
If you return to the area with the T-Rex after you have used the cogs on on the wall and used the lever next to it, you can pick up the cogs again there (at least the one in the cave behind the waterfall at the top respawns).

Expected behaviour:
Puzzle items should not respawn after they have been used.

Notes:
I saved / loaded the game several times after picking up the item and after using it, so this might be a missing flag in the savegame.

**Comment by stohrendorf** [comment]
Issue has been transferred to YouTrack as EE-381.

**Comment by stohrendorf** [comment]
Fix is released now with beta 7.

**Comment by ANoDE85** [comment]
Hi,
I'm using Beta 7.1 and I have noticed that there are still pickups, that respawn after loading - in this case, the first scion piece in Tomb of Qualopec. I picked it up, quicksaved and loaded, and the scion piece was back again.
[quicksave.zip](https://github.com/stohrendorf/EdisonEngine/files/7674974/quicksave.zip)
.
