### ISSUE TITLE
Lara draws holds her guns after loading a savegame where she hangs from a ledge

### ISSUE THREAD

**Issue by ANoDE85** [stohrendorf/EdisonEngine#185]
Engine version: Beta 6.1
Level: The Lost Valley

Current behaviour:
When hanging from a ledge (I used the one from the waterfall where the secret is in the T-Rex area) and saving the game, Lara will hold her pistols when loading this savegame (using quicksave/quickload).

Expected behaviour:
Lara's weapon state should not be changed by saving / loading.

Remarks:
After pulling up from the ledge, the first press to "Draw Weapons" will draw the pistols again.
If "Draw Weapons" is not used, Lara's hands seem to be in "unarmed" mode, i.e. she can grab the ledge again, although her hands hold the pistols.

**Comment by stohrendorf** [comment]
Issue information has been added to YouTrack EE-236.

**Comment by stohrendorf** [comment]
Fix is released now with beta 7.
