### ISSUE TITLE
[Movement] Lara fails to grab certain parts of some ledges

### ISSUE THREAD

**Issue by ANoDE85** [stohrendorf/EdisonEngine#189]
Engine version: Beta 7.1

**Note: This bug is also happening in tombati.exe, so it might be an original engine bug.**

Current behaviour:
Lara fails to grab / pull up on certain parts of some ledges.
I've encountered it with the second bridge in Caves level, see video. Each time when there is a short pause in the video, I am trying to pull up on to the bridge, but nothing happens. When Lara falls to the ground, I have the action button pressed, but she refuses to grab the ledge.

https://user-images.githubusercontent.com/22801244/143896833-e8927bb9-7b5a-416f-b940-71c237e2e855.mp4

Also, a savegame is provided (press action when loading it, otherwise Lara will fall).
You will not be able to pull up at this position, even though it should be possible.
[quicksave.zip](https://github.com/stohrendorf/EdisonEngine/files/7619236/quicksave.zip)

**Comment by stohrendorf** [comment]
Thank you, that video seems very helpful. My first suspicion is that the collision check algorithm for some reason checks the floor height difference, not the actual bridge height. Will investigate this.
