### ISSUE TITLE
Color of non-textured meshes does not match texture color

### ISSUE THREAD

**Issue by ANoDE85** [stohrendorf/EdisonEngine#212]
Lara consists of a few meshes that don't have any textures. Instead they are of a solid colour. This colour differs slightly from the colour of the (default) game textures, resulting in visible lines throughout her character model:
![2022-03-19 14-12-25](https://user-images.githubusercontent.com/22801244/159124578-d6df46bd-e30d-43ac-a5dd-c645f60aaf40.png)

It's not that bin an issue, but it would still look better, if all of Lara's parts would have the same colour.

**Comment by stohrendorf** [comment]
I discovered I was using the wrong formula for color space conversion. This is how it looks now.

![grafik](https://user-images.githubusercontent.com/7853507/159153133-2f5ab73e-a868-486e-a1c0-c1f806998278.png)

Luckily, it's only in the shaders, so you may want to use the attached (fixed) shaders and see if it works better for you.

[shaders.zip](https://github.com/stohrendorf/EdisonEngine/files/8310830/shaders.zip)

**Comment by stohrendorf** [comment]
As I got no response for a while, and the shaders are included in the releases, I'll close this.
