### ISSUE TITLE
Black screen / only sounds is heared

### ISSUE THREAD

**Issue by Sol1vaN** [stohrendorf/EdisonEngine#217]
Hi there!

I want to probe your engine, it looks fantastic.
But, when I play any level, all the screen are black, I only see some effects on particles like chromatic aberration and dust.
The menu looks fine, this happen only when I play the levels of the game.

**What I have done to fix this:**

- I've chequed if disabling all graphical effects to fix this problem, but it still persist.
- Testing with the data of two different versions (my original CD and Steam version)
PD: With Steam version I need to use the tool UniExtract2 to extract the content of _GAME.GOG_ file.

I've attached my log if you can see whats happens on my case.
Also i've attached some screenshots to see the examples.

[edisonengine.log](https://github.com/stohrendorf/EdisonEngine/files/8598157/edisonengine.log)
![2022-04-30 21-47-47](https://user-images.githubusercontent.com/33560454/166129240-e0818eb4-91b3-4058-9432-172dd19aa4d9.png)
![2022-04-30 21-48-38](https://user-images.githubusercontent.com/33560454/166129241-92812dec-12cf-4a50-a6a0-ed51cc460887.png)
![2022-04-30 21-50-37](https://user-images.githubusercontent.com/33560454/166129242-003f0edb-9be4-42aa-9f6a-2246749ff9f9.png)

**Comment by stohrendorf** [comment]
Thanks for the report. I have to admit that I didn't test the engine on NVidia lately. I'll look into this when I find the time.

**Comment by stohrendorf** [comment]
Can you maybe clarify why you used uniextract? That shouldn't be necessary, as the engine supports automatic extraction of game assets from the images of the GOG and steam versions. I'm also not sure whether it works for you now or not, as you wrote "it looks fantastic" (thanks btw) - did you fix it by just re-extracting the data?

**Comment by Sol1vaN** [comment]
> Can you maybe clarify why you used uniextract? That shouldn't be necessary, as the engine supports automatic extraction of game assets from the images of the GOG and steam versions. I'm also not sure whether it works for you now or not, as you wrote "it looks fantastic" (thanks btw) - did you fix it by just re-extracting the data?

I'll test that you say today.
And then I'll comment you 😉

**Comment by stohrendorf** [comment]
What I said wasn't instructions, it was just questions I hoped you could answer so I can understand the issue better.

**Comment by Sol1vaN** [comment]
> What I said wasn't instructions, it was just questions I hoped you could answer so I can understand the issue better.

I've doing some testing and this follow with this:

First of all: I've founded two versions:
- An .7z version (edisonengine-beta-7.1-windows-x64.7z)
- And an installer version that's seems to be the latest (EdisonEngine-1.2.1-win64.exe)

So, yesterday, I have used the .7z version and I followed some instructions by Raina Audron thats says:
"7. Grab your TR1 CD and open it so you can view what is on the disc and copy the contents of FMV
and DATA folders into your own empty FMV and DATA folders in EE."
Source: https://drive.google.com/file/d/1iRz4Svdi_dhmlDNFYeZqyP-wfApWhDoN/view

So for this reason I've supposed to use my own CD of TR1.
The result with this way are the black screen that I've posted before.

And now: I've tested the installer version and I've followed your comment that says "as the engine supports automatic extraction of game assets from the images of the GOG and steam versions"

So, I've uninstalled all my game data from Steam for TR1 and install it againt from zero.
I've followed the installer steps and this happens now (attached screenshot).

So, now I've attached the .log to if you can see some out of order
[edisonengine.log](https://github.com/stohrendorf/EdisonEngine/files/8608137/edisonengine.log)
![Captura de pantalla 2022-05-02 231123](https://user-images.githubusercontent.com/33560454/166401130-56265b62-a7af-42f5-bc90-7655386c108c.png)

**Comment by Sol1vaN** [comment]
Nah! I missed the audio files in the process 🤦‍♂️
Sorry for the dum report. 😓

Anyway, in the manual says "Grab your TR1 CD and copy the contents of DATA folder"
This can confuse to someone. If the Steam version is compatible, the "CD" word need to be removed from the manual I think.

Now the game works fine.

Last question:
The "7.1 version vs 1.2.1" of the releases (7z vs Installer) what are more recent? For numbers the 7.1 are better, not?
![Sin título-2](https://user-images.githubusercontent.com/33560454/166401986-188713ba-5444-4cd0-9372-eb90a82d6b9e.jpg)
?

**Comment by Sol1vaN** [comment]
https://www.youtube.com/watch?v=lUVQz6_-vxc

Nou! all the problem is about the MSI Afterburner 😂😂😂😂
I've closed it and the game works fine (in both cases).

Well, all my testing I hope helps to add this condition in the page (don't use Afterburner).
![Sin título-3](https://user-images.githubusercontent.com/33560454/166402567-033c3086-9487-4792-b945-ec056f9f883a.jpg)
![Sin título-4](https://user-images.githubusercontent.com/33560454/166402569-9268da74-d7b7-47ed-a50a-15088b78325e.jpg)

**Comment by stohrendorf** [comment]
* The "*beta* 7.1" version is horribly outdated, the current version is 1.2.1.
* The TLS issue is a big problem, I've already seen it, but it was for specifically crafted test version, so I didn't think much of it.
* I'll look into why a physical CD doesn't seem to work, but I suspect it's because you circumvented the installer process.
* I'll keep MSI Afterburner in mind.
