### ISSUE TITLE
Add HID input remapping

### ISSUE THREAD

**Issue by stohrendorf** [stohrendorf/EdisonEngine#94]
Allow remapping keys to actions.
- [x] show human-readable key names
- [ ] gamepad input axes/hats/etc.

![image](https://user-images.githubusercontent.com/7853507/108681699-bf466700-74ef-11eb-83d5-6ac334c9d3a5.png)

**Comment by Richard-L** [comment]
Is this related to the UI for mapping as well?

**Comment by stohrendorf** [comment]
> Is this related to the UI for mapping as well?

It is required to actually be able to build such a UI.
